# Site Info
title: Connector Development Blog
tagline: 'Building a curated profile service to connect influencers and ideas'
description: 'Development log and notes'
baseurl: "/connector"
url: http://simoncozens.github.io/
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Simon Cozens
  gravatar: 97f68b9e757f8150fc0b4c9aed1ee6db
  contact:
    github:    https://github.com/simoncozens
    twitter:   https://twitter.com/simoncozens

# Navigation (2nd level links supported)
nav:
  Blog:           
    - '/'
    - { Categories: '/categories/' }
    - { Tags: '/tags/' }

# Where are tags and categories displayed
tag_page: '/tags/'
category_page: '/categories/'

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: '' # leave blank if you don't want google analytics
disqus_short_name: 'simoncozens' # leave blank if you don't want disqus

